### ISSUE TITLE
require-dev dependencies

### ISSUE THREAD

**Issue by armandabric** [cofounders/googletagmanager#2]
Could you define the grunt related dependencies in the `devDependencies` key of the `package.json` file ?

I do not use grunt, so do not want to download it :o)

**Comment by sebdeckers** [comment]
Fixed https://github.com/cofounders/googletagmanager/commit/e2a2ed9515ec3019e85450b05f31d8d0891d60f3
Published https://github.com/cofounders/googletagmanager/commit/4eb7e900aba5e391b5b807ade80d6a859e6d869e

**Comment by armandabric** [comment]
Thanks!
